mapName: FDG DAT
Regions:
  - name: kitchen
    min:
      x: 4
      y: 5.83
    max:
      x: 7.58
      y: 7.13
  - name: lounge
    min:
      x: 6.22
      y: 1.3
    max:
      x: 8.3
      y: 4.16

